version: 2
jobs:
  build:
    docker:
      - image: openchemistry/mongochemserver:latest
        environment:
          - CIRCLE_BRANCH: ${CIRCLE_BRANCH}
          - CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}
      - image: mongo:latest
      - image: openchemistry/openbabel:latest
      - image: openchemistry/avogadro:latest
    working_directory: /mongochemserver
    steps:
      - checkout
      - run:
          # See: https://github.com/girder/girder/issues/3298
          name: Update packages to be compatibile with girder
          command: >
            pip install -U six requests jsonschema importlib-metadata boto3 urllib3

      - run:
          name: Install requirements
          command: >
            pip install -U --no-cache-dir -r /mongochemserver/requirements-dev.txt
      - run:
          name: Install the plugins
          command: >
            pip install -e /mongochemserver/girder/molecules

      - run:
          name: Install girder_pytest
          command: >
            git clone https://github.com/girder/girder.git /girder_pytest &&
            cd /girder_pytest &&
            pip install --no-cache-dir -r requirements-dev.txt

      - run:
          name: Run pytest
          command: 'pytest ./girder/molecules/plugin_tests/'

workflows:
  version: 2
  ci:
    jobs:
      - build
